import Head from 'next/head';
import * as tf from '@tensorflow/tfjs';

import styles from '@/styles/Home.module.css';

export default function Home() {
  const handleRunTraining = () => {
    const ts = tf.tensor([
      [1, 1, 1],
      [1, 1, 1],
      [1, 1, 1],
    ]);
    tf.print(ts);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleRunTraining}>Training</button>
      </main>
    </>
  );
}
